name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check file
        run: |
          sudo apt-get update,
          sudo apt-get install -y agda agda-stdlib,
          agda Hello.agda
